version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   GITHUB_USERNAME: ${GITHUB_USERNAME}
      #   GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8081:5001" #backend
      - "8080:8501" #frontend
