version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   GITHUB_USERNAME: ${GITHUB_USERNAME}
      #   GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8080:9874"
      - "443:443"
    command: python3 main.py
    # command: tail -f /dev/null

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   env_file:
  #     - .env
