version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8080:5000"
      - "443:443"
    command: python3 /opt/NexoSphere/sourceCode/hello.py
