name: Run Docker Container

on:
  workflow_dispatch:  # Manual trigger
    branches:
      - nishant
  pull_request:
    branches:
      - nishant

jobs:
  run-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image using Docker Compose
        run: |
          docker-compose build

      - name: Run the Docker container using Docker Compose
        run: |
          docker-compose up -d
